/**
 * Track split distribution — fans a track-revenue event out into per-recipient
 * `track_split_payouts` rows according to the master splits on the track.
 *
 * Called from the NOWPayments webhook on the 'finished' branch for:
 *   - track purchases (every completed buy)
 *   - tips (only when the tip carries a track_id)
 *
 * Distribution rules:
 *   - No accepted/pending splits for this (track, 'master') → one 'credited'
 *     row to the track owner for the full pool.
 *   - Otherwise: for each accepted row (including the owner's auto-managed
 *     accepted row) write a 'credited' row; for each pending row write an
 *     'escrowed' row. Escrow gets released to the collaborator on
 *     splits.accept, or returned to the owner on splits.reject/revoke.
 *
 * Largest-remainder rounding so per-row cents sum exactly to the pool.
 *
 * Idempotent on (sourceType, sourceId) — re-invocations (e.g. webhook retries
 * after a transient DB failure) do nothing.
 */

import { db, trackSplits, trackSplitPayouts, tracks } from '@opynx/db';
import { and, eq, sql } from 'drizzle-orm';

interface DistributeArgs {
  sourceType: 'track_purchase' | 'tip';
  sourceId: string;
  trackId: string;
  poolCents: number;
}

export async function distributeTrackSplitPayouts(args: DistributeArgs): Promise<void> {
  const { sourceType, sourceId, trackId, poolCents } = args;

  if (poolCents <= 0) return;

  // Idempotency: bail if rows already exist for this source.
  const existing = await db
    .select({ id: trackSplitPayouts.id })
    .from(trackSplitPayouts)
    .where(
      and(
        eq(trackSplitPayouts.sourceType, sourceType),
        eq(trackSplitPayouts.sourceId, sourceId)
      )
    )
    .limit(1);
  if (existing.length > 0) return;

  const track = await db.query.tracks.findFirst({
    where: eq(tracks.id, trackId),
    columns: { id: true, userId: true },
  });
  if (!track) {
    console.warn(`[split-distribution] Track ${trackId} not found for ${sourceType} ${sourceId}`);
    return;
  }

  // Only 'accepted' and 'pending' rows participate. Rejected/revoked are terminal
  // and their bp has already been returned to the owner row by the splits router.
  const rows = await db
    .select({
      id: trackSplits.id,
      collaboratorUserId: trackSplits.collaboratorUserId,
      percentBp: trackSplits.percentBp,
      status: trackSplits.status,
    })
    .from(trackSplits)
    .where(
      and(
        eq(trackSplits.trackId, trackId),
        eq(trackSplits.splitType, 'master'),
        sql`${trackSplits.status} IN ('accepted', 'pending')`
      )
    );

  // No splits materialized yet → owner is implicit 100%.
  if (rows.length === 0) {
    await db.insert(trackSplitPayouts).values({
      sourceType,
      sourceId,
      trackId,
      recipientUserId: track.userId,
      trackSplitId: null,
      splitType: 'master',
      percentBp: 10000,
      amountCents: poolCents,
      status: 'credited',
    });
    return;
  }

  // Distribute via largest-remainder. Each row's floor share gets allocated
  // first, then leftover cents go to the largest-bp rows (ties broken by
  // creation order — stable iteration of `rows` from the DB query).
  const distribution = rows.map((r) => {
    const floor = Math.floor((poolCents * r.percentBp) / 10000);
    return {
      trackSplitId: r.id,
      recipientUserId: r.collaboratorUserId,
      percentBp: r.percentBp,
      status: r.status as 'accepted' | 'pending',
      cents: floor,
    };
  });

  const allocated = distribution.reduce((sum, d) => sum + d.cents, 0);
  let remainder = poolCents - allocated;

  if (remainder > 0) {
    const order = [...distribution].sort((a, b) => b.percentBp - a.percentBp);
    let i = 0;
    while (remainder > 0) {
      order[i % order.length].cents += 1;
      remainder -= 1;
      i += 1;
    }
  }

  await db.insert(trackSplitPayouts).values(
    distribution.map((d) => ({
      sourceType,
      sourceId,
      trackId,
      recipientUserId: d.recipientUserId,
      trackSplitId: d.trackSplitId,
      splitType: 'master' as const,
      percentBp: d.percentBp,
      amountCents: d.cents,
      status: d.status === 'accepted' ? ('credited' as const) : ('escrowed' as const),
    }))
  );
}

/**
 * Refund handler — flips all payout rows for a source to 'clawed_back' so
 * they stop counting in earnings. Sibling owner-credit rows that were
 * generated by previous 'reject'/'revoke' actions on this source's escrow
 * rows are NOT chased; they remain credited (matches the subscription
 * commission clawback pattern: snapshot at clawback time, no cascade).
 */
export async function clawBackTrackSplitPayouts(
  sourceType: 'track_purchase' | 'tip',
  sourceId: string
): Promise<number> {
  const updated = await db
    .update(trackSplitPayouts)
    .set({ status: 'clawed_back', updatedAt: new Date() })
    .where(
      and(
        eq(trackSplitPayouts.sourceType, sourceType),
        eq(trackSplitPayouts.sourceId, sourceId),
        sql`${trackSplitPayouts.status} IN ('credited', 'escrowed', 'released', 'returned')`
      )
    )
    .returning({ id: trackSplitPayouts.id });
  return updated.length;
}
